### ISSUE TITLE
Pre-AndroidX Library Using AndroidX Dependencies

### ISSUE THREAD

**Issue by msilverman92** [reddit/IndicatorFastScroll#20]
Noticed when compiling the pre-AndroidX version of the library, that it's still requiring the androidx.core » core-ktx dependency. This should probably be changed/removed?

**Comment by DSteve595** [comment]
You probably want to checkout `fff26f9`.

**Comment by msilverman92** [comment]
I see that it's been removed in that commit, but it's still causing some issues.
Maven also shows it as a dependency still.
https://mvnrepository.com/artifact/com.reddit/indicator-fast-scroll/1.0.1

**Comment by DSteve595** [comment]
That's strange, maybe something is bringing it in as a transitive dependency.
Can you expand on the issues you're getting?

**Comment by msilverman92** [comment]
Possibly. It's not that it's causing any issues with the library or functionality itself, but it is causing my spotless/circle check to fail and had to manually ignore that android x dependency.

**Comment by DSteve595** [comment]
Looks like 1.0.1 was released before the KTX lib was removed. That's why the maven dependency still shows up.
By ignoring the dependency, do you mean excluding via `exclude group: 'androidx.core'`?

**Comment by msilverman92** [comment]
Ah, yes sorry I had to manually exclude it.
