### ISSUE TITLE
error: supertypes of the following classes cannot be resolved...

### ISSUE THREAD

**Issue by enricocid** [reddit/IndicatorFastScroll#21]
On Android Studio with version 1.1.1:

> error: supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath.

![Senza nome](https://user-images.githubusercontent.com/7274841/64476833-09b91400-d194-11e9-9393-884d1432611b.png)

I've already tried to invalidata cache/restart and to clean and rebuild the project. The problem persists with the 1.1.1 version of the lib.

**Comment by DSteve595** [comment]
Try adding ConstraintLayout as a dependency. It's probably packaged as an `implementation` dependency, which is a mistake. Can fix.

**Comment by enricocid** [comment]
Ok, gonna try. Just to complete my report: this problem is not present on 1.1.0.

**Comment by DSteve595** [comment]
Should be fixed by 1.2.0.
