### ISSUE TITLE
ViewPager: FastScrollerThumbView not being hidden after changing page

### ISSUE THREAD

**Issue by enricocid** [reddit/IndicatorFastScroll#22]
Hello,

I'm in the process of rewriting from scratch an app and I'm now using **ViewPager**.

I noticed that if you swipe and accidentaly touch the Fast Scroll Indicator the **thumb view is shown remaining visible even if the touch is finished**.
If You touch the indicator the thumb gets hidden.

Video showing the issue: https://youtu.be/Q-6w3hpBWEA

This is happening in lib version **1.1.0**, Android version: **Oreo**  :)

**Comment by DSteve595** [comment]
Confirmed, thanks for the report! We probably need to handle MotionEvents (`ACTION_CANCEL`?) a bit better. Will check it out.

**Comment by DSteve595** [comment]
Should be fixed by 1.2.0.
