### ISSUE TITLE
Change gravity for labels

### ISSUE THREAD

**Issue by n00bman** [reddit/IndicatorFastScroll#26]
Currently gravity is set to CENTER and there is no way to change it. Class is final and we can't inherit from it to change behavior. Can you add method to change gravity or make class not final ?

**Comment by DSteve595** [comment]
That shouldn't be a problem. Would you mind describing your use case?

**Comment by n00bman** [comment]
Yes. I've got a design where indicator labels are gravity to the top of the screen. Currently I can't change this. See screenshots
1) What is now
![Screenshot from 2019-10-04 10-26-42](https://user-images.githubusercontent.com/1682160/66183233-7ccd8180-e691-11e9-8470-27265d4e9f7c.png)
2) What I need
![Screenshot from 2019-10-04 10-29-43](https://user-images.githubusercontent.com/1682160/66183309-e9e11700-e691-11e9-8051-21bfe7566059.png)

**Comment by DSteve595** [comment]
I see. You can probably achieve this by making the height `wrap_content` and aligning it to the top of your layout. Feel free to send your layout.

**Comment by n00bman** [comment]
Thx
