### ISSUE TITLE
thumbColor doesn't work

### ISSUE THREAD

**Issue by MrZ3T4** [reddit/IndicatorFastScroll#28]
From **layout, styles or code** the color doesn't apply

I tried with:

**_app:thumbColor="@color/myColor"_
_<_item name="thumbColor">myColor</item_>_
_fastThumb.setThumbColor(ColorStateList.valueOf(int myColor));_**

The other attributes work perfectly
I am using **java**

**Comment by DSteve595** [comment]
Hmm, will take a look.

**Comment by DSteve595** [comment]
Can't reproduce this on my end. May need more information. If you can give a small sample of this not working, please put it here, and I'll reopen.

**Comment by kirill-sysoev** [comment]
I have reproduced this problem in my project.
After plenty of time spent researching, I found out, that this had happened because my FastScrollerThumbView tag had had similar Id with tag in library layout - fast_scroller_thumb.
