### ISSUE TITLE
Horizontal layout

### ISSUE THREAD

**Issue by enricocid** [reddit/IndicatorFastScroll#30]
Hello,

So I was trying to solve an open issue on my app where the user asked to add land layout support.
Anyway, during the development I noticed that Indicator Fast Scroll gets cut as vertical space is reduced.
Do you think it is possible to have horizontal indicator or it is just a bad design choice?
Any idea on how to solve this problem ? (Note: the source code for these changes is still not available, but I can share layout here if needed).
Thanks anyway.

![Screenshot_20191226-174506](https://user-images.githubusercontent.com/7274841/71483318-9224f880-2807-11ea-8930-8b1bbc662ade.png)

**Comment by DSteve595** [comment]
Adding support for a horizontal layout should be doable, but I'm not sure using it would be very nice to use.
Some ideas:
- Use `showIndicator` to reduce the amount of letters show ([example](https://github.com/reddit/IndicatorFastScroll/blob/master/sample/src/main/java/com/reddit/indicatorfastscroll/sample/examples/FilteredFragment.kt#L58-L61)
- Reduce the text size
- Set a lower `scaleX`/`scaleY`

**Comment by enricocid** [comment]
You are right. I tried, just out of curiosity, to quickly fake horizontal scroller with a recycler view. It doesn't look so good and usability also is affected.

I tried Your solution (showIndicator + scale) and it is ok now. You can close this issue. Thanks for the quick reply!! :)
