### ISSUE TITLE
minSdkVersion (16)

### ISSUE THREAD

**Issue by jacobson** [reddit/IndicatorFastScroll#32]
This actually may be a feature request instead, but for me, it is an issue:

`ERROR: Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.reddit:indicator-fast-scroll:1.2.1] 
indicator-fast-scroll-1.2.1/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.reddit.indicatorfastscroll" to force usage (may lead to runtime failures)
`

**Comment by DSteve595** [comment]
It's not likely that we'll work on this, since more and more applications are raising their minSdkVersions to 21. Sorry about that. Will gladly take a PR, though.
