### ISSUE TITLE
Make isSetup getter public

### ISSUE THREAD

**Issue by Dambakk** [reddit/IndicatorFastScroll#34]
It is useful to be able to wrap the `setupWithRecyclerView` call in an if statement that checks if the fastscroller is setup or not instead of using a try catch.

**Comment by DSteve595** [comment]
I would instead suggest only calling `setupWithRecyclerView` once, as you set up your view.

**Comment by Dambakk** [comment]
Not a use case where calling it mutliple times is easier, but in my app, if the user is in a fragment with a fastscroller, clicks further in to the next fragment, and then press back to go back to the fragment with the fastscroller, the observer callback on the data will be triggered which in turn will call the `setupWithRecyclerView`. Currently I wrap it in a try catch, but I would rather use a simple if statement.

**Comment by DSteve595** [comment]
>the observer callback on the data will be triggered which in turn will call the `setupWithRecyclerView`

Would you mind expanding on this?

`setupWithRecyclerView` isn't intended to be called upon observing some data changes. It's meant to be called once. Your `(position) -> Indicator` lambda can freely change what it's doing. That might be where you want to make changes via your observer.

**Comment by Dambakk** [comment]
I don't understand. The `setupWithRecyclerView` takes a lambda to map element at a position to an indicator. Doesn't that mean I have to wait until I get the data before I can call the setup method?

**Comment by DSteve595** [comment]
Nope. The lambda is called whenever the contents of your RecyclerView changes. If there's no data yet, it won't be called yet.

If you're able to post some code from your Fragment, I can try to show an example of how you'd hook it up.

**Comment by Dambakk** [comment]
Yes, please, that's very kind of you! :) 

I use a `ViewModel` and observes some `LiveData`. I also use ktx view extensions.

```kotlin
class PeopleListFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_people_list, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupRecycler(view) // LayoutManager, adapter, etc
        peoplesViewModel.users.observeListUntilNotEmpty(this) { updatedUsers ->
            updateAdapter(updatedUsers, withHeaders = true)
            configureFastScroller(updatedUsers)
        }
    }


    private fun configureFastScroller(elements: List<PeopleListData>) {
        try {
            fastscroller.apply {
                setupWithRecyclerView(peopleList,
                    useDefaultScroller = false,
                    getItemIndicator = { position ->
                        if (position >= elements.size) null
                        val item = elements[position]
                        val indicatorText = item.user.givenName?.first().toString()
                        FastScrollItemIndicator.Text(indicatorText)
                    }
                )
            }
            fastscroller_thumb.setupWithFastScroller(fastscroller)
        } catch (e: Exception) {
            Timber.e(e, "Fastscroller already setup")
        }
    }
}
```

**Comment by DSteve595** [comment]
Do you keep an instance of `updatedUsers` anywhere? There are a few different solutions that'd work here, up to your personal preference. If you've got an instance already kept, it'll be very simple.

Also:
I noticed you've got a `withHeaders = true` argument for your adapter. Keep in mind that in `getItemIndicator = { position ->`, the `position` is for the item in the RecyclerView. So if you have a header at position `0`, and your `PeopleListData`s begin at position `1`, reading `elements[position]` is an off-by-one error.

**Comment by Dambakk** [comment]
Yes, I do have a class variable that holds the `updatedUsers`, initially `emptyList`. So `configureFastScroller` is only called once when the observe callback is called. But, when opening another fragment from this one, and then going back to the list fragment, the callback is run again causing the exception.

Yeah, thanks, I also have a custom itemIndicatorSelectedCallback to account for the headers :)  (also a part of the `configureFastScroller` method.

```kotlin
fastscroller.itemIndicatorSelectedCallbacks += object :
            FastScrollerView.ItemIndicatorSelectedCallback {
            override fun onItemIndicatorSelected(
                indicator: FastScrollItemIndicator,
                indicatorCenterY: Int,
                itemPosition: Int
            ) {
                // { itemPosition - 1} to account for the header element
                peopleList.apply {
                    stopScroll()
                    smoothScrollToPosition(itemPosition - 1)
                    peopleListAppBarLayout.setExpanded(false, true)
                }
            }
        }
```

So, when do you suggest me calling the configure call? What is "best practice"? :)

**Comment by DSteve595** [comment]
Calling it once should do it:
```kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)
    setupRecycler(view) // LayoutManager, adapter, etc
    setupFastScroller()
    peoplesViewModel.users.observeListUntilNotEmpty(this) { updatedUsers ->
        updateAdapter(updatedUsers, withHeaders = true)
        configureFastScroller(updatedUsers)
    }
}
private fun setupFastScroller() {
    fastscroller.apply {
        setupWithRecyclerView(peopleList,
            useDefaultScroller = false,
            getItemIndicator = { position ->
                if (position >= updatedUsers.size) null
                val item = updatedUsers[position]
                val indicatorText = item.user.givenName?.first().toString()
                FastScrollItemIndicator.Text(indicatorText)
            }
        )
    }
    fastscroller_thumb.setupWithFastScroller(fastscroller)
}
```

**Comment by Dambakk** [comment]
But I need the data before I can configure it, right? And I don't have the data yet in onViewCreated. Or is there something I have misunderstood?

**Comment by DSteve595** [comment]
No, you don't. You just need a provider that can return an indicator _from_ a position. If there's no data yet, there's no position, and thus nothing to call. The `getItemIndicator` lambda is that provider.
