### ISSUE TITLE
Open Keyboard cuts bar

### ISSUE THREAD

**Issue by jbirtel** [reddit/IndicatorFastScroll#35]
When having a searchbar in the same fragment as the index bar and then opening the keyboard via the searchbar, the bar is compressed and only the indices until L (in my case) were visible, but L matched to Z.
At the moment fixed this with having a listener that listens for the keyboard to open and then sets the bar to invisible and to visible again if keyboard closes.
![Library Bug](https://user-images.githubusercontent.com/57353201/85139150-4d24d080-b244-11ea-85a7-4260e8925416.jpg)

**Comment by enricocid** [comment]
You could hide the indicator while interacting with the search view.
I mean, do You really need the fast scroller while filtering?

**Comment by jbirtel** [comment]
I actually solved it like that but thought it could be nice to know for you guys. Maybe others want to use the indicator even when keyboard is open. Then it could be helpful to have that fixed, as there is a mismatch between ThumbIndicator and indicator bar.

**Comment by enricocid** [comment]
Another solution: reduce the number of the letters to show, like suggested [here](https://github.com/reddit/IndicatorFastScroll/issues/30#issuecomment-569092626)

Just a question: are you setting the following attr in the manifest (main activity tag)?

android:windowSoftInputMode="adjustPan">

I'm asking as I didn't experienced that issue before using this attr.

**Comment by jbirtel** [comment]
No, I did not set that attribute, Maybe I’ll try this in a later version. I think the solution to hide the indicator is actually fine. Thanks for your help :)

**Comment by DSteve595** [comment]
The mismatch could definitely be considered a bug. Overall, I'm with @enricocid on this one: hiding it seems like a good idea. I'm not sure what a good default behavior would even be.
