### ISSUE TITLE
Dynamic text size

### ISSUE THREAD

**Issue by rektitralph** [reddit/IndicatorFastScroll#37]
Is there a way to make the text/alphabet size dynamic depending on the screen size? Because I need to show all the letters but I need make them fit. Thanks in advance

**Comment by enricocid** [comment]
https://github.com/reddit/IndicatorFastScroll/issues/30#issuecomment-569092626

You can try the 2nd suggestion, i.e. set a different X, Y scale for the fastscroller view.

**Comment by rektitralph** [comment]
I will try this. Thank you for the suggestions
