### ISSUE TITLE
SwipeToRefresh IndexOutOfBoundsException issue

### ISSUE THREAD

**Issue by rektitralph** [reddit/IndicatorFastScroll#38]
Hi, I am currently building a list using indicator fast scroll. I'm only setting the recyclerview once in onCreate(). But after 
I implemented swipeToRefresh to update the list, I encountered IndexOutOfBoundsException. It would be great help if someone can enlighten me on this. Thank you

**Comment by DSteve595** [comment]
Would you be able to share a reproducible case? Without it, it's hard to narrow down what might be happening.

**Comment by enricocid** [comment]
When you update the list you should also use notifyDataSetChanged in adapter to notify attached obsedvers that data has changed.
So you have to update the list and then use adapter.notifyDataSetChanged()

**Comment by rektitralph** [comment]
@DSteve595 

Here is where I initialize the adapter (btw I'm using Groupie library)
```
contactAdapter = GroupAdapter()
rv_contacts.apply {
      layoutManager = LinearLayoutManager(requireActivity())
      adapter = contactAdapter
}
```

And this is how I setup the fastScrollerView (I set a static alphabet because whenever I observe list from viewmodel, I receive the error that you can only setup the recyclerview once)
```
val alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ#".toCharArray()
fastScrollerView.setupWithRecyclerView(
            rv_contacts,
            { position ->
                FastScrollItemIndicator.Text(
                    alphabet[position].toString()
                )
            }
)
fastscroller_thumb.setupWithFastScroller(fastScrollerView)
```

Then I'll observe the data from local database here using NetworkBoundResource
```
contactViewModel.loadContacts(forceRefresh).observe(viewLifecycleOwner, Observer { resource ->
           when (resource) {
                     is Resource.Loading -> {
                         showLoading()
                     }
                     is Resource.Success -> {
                         showSuccess(resource)
                     }
                     is Resource.Error -> {
                         showError(resource)
                     }
            }
})
```

After I receive the list, I'll add it to the section then to the adapter
```        
section.clear()
section.addAll(items)
contactAdapter.add(section)
```

It works fine on the first load but by the time I call the observer again using swipeRefresh, I'd get the IndexOutOfBoundsException

**Comment by rektitralph** [comment]
Hi again @DSteve595 and @enricocid. I already fixed the problem. It was an implementation issue, my bad. I'll be closing this issue now. Thanks
