### ISSUE TITLE
Fast scroll within scrollbar

### ISSUE THREAD

**Issue by vipatronon** [reddit/IndicatorFastScroll#39]
Is it possible to make fast scroll behaviour in a scrollbar?
Like this

![image](https://user-images.githubusercontent.com/9328789/103369787-cf226b80-4aa9-11eb-9396-63b41f88f9ab.png)

Thanks in advance

**Comment by DSteve595** [comment]
Not with this library. You may want to try another, like [zhanghai/AndroidFastScroll](https://github.com/zhanghai/AndroidFastScroll).
