### ISSUE TITLE
Custom scrollers are too intensive

### ISSUE THREAD

**Issue by diceroll123** [reddit/IndicatorFastScroll#5]
If you open the `CUSTOM SCROLL` sample and slide up and down the indicator list at a fast _yet still sane_ speed, you'll start to see this come up in the Logcat: `RecyclerView: Smooth Scroll action is being updated too frequently. Make sure you are not changing it unless necessary`

I regret to inform you that this also happens in the reddit app in the Browse tab, with a bonus Logcat entry: `VibratorService: Failed to perform effect (2)`

**Comment by DSteve595** [comment]
Ideally we'd have a fix for this, but I haven't found any actual negative side effects of this repeated call. Realistically, I think this is a won't-fix, as I can't come up with any solutions that don't involve slowing down the responsiveness of the scrolling. Closing for now. Can reopen if something comes up down the line.
