### ISSUE TITLE
Set up multiple times

### ISSUE THREAD

**Issue by bernaferrari** [reddit/IndicatorFastScroll#7]
How do I reset it and set-up again, when data from RecyclerView changes? There is no method, after isSetup is true, there is no going back.

**Comment by DSteve595** [comment]
There isn't a need to, since it watches your RecyclerView's adapter for data changes and updates as needed.

**Comment by bernaferrari** [comment]
Oh, nice!

**Comment by bernaferrari** [comment]
@DSteve595 If I open the app in split-screen mode, the IndicatorFastScroll doesn't reload and when you tap on it, it goes to wrong values.

**Comment by bernaferrari** [comment]
Also, what should I do with filtering? It displays the wrong indexes, since the list has been updated (filtered):

![screenshot_20181006-015627_sdk monitor](https://user-images.githubusercontent.com/351125/46567580-86e86300-c90b-11e8-920c-aa530200a916.jpg)

**Comment by DSteve595** [comment]
Hmm, how are you populating the models? Would you be able to post your code?

**Comment by bernaferrari** [comment]
Oh.. In the end, it was my mistake and everything is working fine now. Thanks for all the help, I'll let you know when the app is ready!

**Comment by bernaferrari** [comment]
My app is up: https://github.com/bernaferrari/SDKMonitor

**Comment by DSteve595** [comment]
Looks great, nice idea and design!
