### ISSUE TITLE
Problem with androidx

### ISSUE THREAD

**Issue by PFittech** [reddit/IndicatorFastScroll#8]
{"kind":"error","text":"Program type already present: androidx.core.graphics.PathSegment","sources":[{}],"tool":"D8"}

**Comment by PFittech** [comment]
OK I find solution>

 implementation ('com.reddit:indicator-fast-scroll:1.0.1') {
        exclude group: 'androidx.core'
    }

and I implement 'androidx.core:core-ktx:1.0.1'

**Comment by DSteve595** [comment]
Appreciate the report! Working on a fix.

**Comment by DSteve595** [comment]
Version 1.1.0-beta1 is released, which uses AndroidX. Going forward, releases of the library will likely only support AndroidX. Version 1.0.1 can still be used in projects not AndroidX. If a dependency issue arises from a project including a different version of KTX, the workaround you mentioned above will help.
